# Generated by Django 2.1.1 on 2018-12-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puliapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foodlist',
            fields=[
                ('cuisine', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('add', models.CharField(max_length=70)),
                ('tel', models.CharField(db_column='tel', max_length=70)),
                ('url', models.CharField(max_length=60)),
                ('other', models.TextField()),
            ],
            options={
                'db_table': 'foodlist',
                'managed': False,
            },
        ),
    ]
